# Generated by Django 4.2.6 on 2023-11-09 06:40

from django.db import migrations, models

# Definir la migración
class Migration(migrations.Migration):

# Configuración inicial
    initial = True

    dependencies = [
    ]
# Operaciones a se realizaran en la bd
    operations = [
        migrations.CreateModel(
            name='pilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('respiracion', models.CharField(max_length=30)),
                ('edad', models.IntegerField(default=14)),
            ],
        ),
    ]
