# Generated by Django 4.2.6 on 2023-11-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0003_entrada_delete_datosprueba_delete_pilar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='contenido',
            field=models.TextField(max_length=800),
        ),
    ]
