# Generated by Django 4.2.6 on 2023-11-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_alter_entrada_contenido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('Comentario', models.TextField(max_length=600)),
            ],
        ),
    ]
