# Generated by Django 4.2.6 on 2023-11-12 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0005_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='Comentario',
            field=models.TextField(max_length=400),
        ),
    ]
